[2025-08-31 23:32:37,628] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-08-29T19:42:01.597816+00:00 [queued]>
[2025-08-31 23:32:37,654] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-08-29T19:42:01.597816+00:00 [queued]>
[2025-08-31 23:32:37,655] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-31 23:32:37,655] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2025-08-31 23:32:37,655] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-31 23:32:37,689] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stream_hdfs> on 2025-08-29 19:42:01.597816+00:00
[2025-08-31 23:32:37,700] {standard_task_runner.py:52} INFO - Started process 188 to run task
[2025-08-31 23:32:37,703] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'stream_hdfs', 'scheduled__2025-08-29T19:42:01.597816+00:00', '--job-id', '380', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpw7815ove', '--error-file', '/tmp/tmp5bvjekqf']
[2025-08-31 23:32:37,705] {standard_task_runner.py:80} INFO - Job 380: Subtask stream_hdfs
[2025-08-31 23:32:37,742] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-31 23:32:37,870] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.stream_hdfs scheduled__2025-08-29T19:42:01.597816+00:00 [running]> on host 5d7670b258c3
[2025-08-31 23:32:38,074] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=stream_hdfs
AIRFLOW_CTX_EXECUTION_DATE=2025-08-29T19:42:01.597816+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-29T19:42:01.597816+00:00
[2025-08-31 23:32:38,075] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-31 23:32:38,076] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n/home/***/.local/bin/spark-submit   --master local[*]   --conf spark.hadoop.fs.defaultFS=hdfs://namenode:9000   --conf spark.hadoop.dfs.client.use.datanode.hostname=true   --conf spark.sql.adaptive.enabled=false   --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1   /opt/***/scripts/pyspark/streaming.py']
[2025-08-31 23:32:38,093] {subprocess.py:85} INFO - Output:
[2025-08-31 23:32:38,116] {subprocess.py:92} INFO - /opt/spark-3.3.1-bin-hadoop3/bin/load-spark-env.sh: line 68: ps: command not found
[2025-08-31 23:32:42,056] {subprocess.py:92} INFO - :: loading settings :: url = jar:file:/opt/spark-3.3.1-bin-hadoop3/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-08-31 23:32:42,198] {subprocess.py:92} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-08-31 23:32:42,198] {subprocess.py:92} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-08-31 23:32:42,204] {subprocess.py:92} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-08-31 23:32:42,206] {subprocess.py:92} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-ee111f11-a6ad-4dc4-bf82-e63a1240ee48;1.0
[2025-08-31 23:32:42,206] {subprocess.py:92} INFO - 	confs: [default]
[2025-08-31 23:32:45,682] {subprocess.py:92} INFO - :: resolution report :: resolve 3476ms :: artifacts dl 1ms
[2025-08-31 23:32:45,682] {subprocess.py:92} INFO - 	:: modules in use:
[2025-08-31 23:32:45,682] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-08-31 23:32:45,683] {subprocess.py:92} INFO - 	|                  |            modules            ||   artifacts   |
[2025-08-31 23:32:45,683] {subprocess.py:92} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-08-31 23:32:45,683] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-08-31 23:32:45,683] {subprocess.py:92} INFO - 	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2025-08-31 23:32:45,683] {subprocess.py:92} INFO - 	---------------------------------------------------------------------
[2025-08-31 23:32:45,689] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,689] {subprocess.py:92} INFO - :: problems summary ::
[2025-08-31 23:32:45,689] {subprocess.py:92} INFO - :::: WARNINGS
[2025-08-31 23:32:45,689] {subprocess.py:92} INFO - 	problem while downloading module descriptor: https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.1/spark-sql-kafka-0-10_2.12-3.3.1.pom: impossible to move part file to definitive one: /home/***/.ivy2/cache/org.apache.spark/spark-sql-kafka-0-10_2.12/ivy-3.3.1.xml.original.part -> /home/***/.ivy2/cache/org.apache.spark/spark-sql-kafka-0-10_2.12/ivy-3.3.1.xml.original (311ms)
[2025-08-31 23:32:45,690] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,690] {subprocess.py:92} INFO - 		module not found: org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1
[2025-08-31 23:32:45,690] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,690] {subprocess.py:92} INFO - 	==== local-m2-cache: tried
[2025-08-31 23:32:45,690] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,690] {subprocess.py:92} INFO - 	  file:/home/***/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.1/spark-sql-kafka-0-10_2.12-3.3.1.pom
[2025-08-31 23:32:45,690] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,690] {subprocess.py:92} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1!spark-sql-kafka-0-10_2.12.jar:
[2025-08-31 23:32:45,690] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,691] {subprocess.py:92} INFO - 	  file:/home/***/.m2/repository/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.1/spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-08-31 23:32:45,691] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,691] {subprocess.py:92} INFO - 	==== local-ivy-cache: tried
[2025-08-31 23:32:45,691] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,691] {subprocess.py:92} INFO - 	  /home/***/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.3.1/ivys/ivy.xml
[2025-08-31 23:32:45,691] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,691] {subprocess.py:92} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1!spark-sql-kafka-0-10_2.12.jar:
[2025-08-31 23:32:45,691] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,692] {subprocess.py:92} INFO - 	  /home/***/.ivy2/local/org.apache.spark/spark-sql-kafka-0-10_2.12/3.3.1/jars/spark-sql-kafka-0-10_2.12.jar
[2025-08-31 23:32:45,692] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,692] {subprocess.py:92} INFO - 	==== central: tried
[2025-08-31 23:32:45,692] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,692] {subprocess.py:92} INFO - 	  https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.1/spark-sql-kafka-0-10_2.12-3.3.1.pom
[2025-08-31 23:32:45,692] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,692] {subprocess.py:92} INFO - 	==== spark-packages: tried
[2025-08-31 23:32:45,692] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,692] {subprocess.py:92} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.1/spark-sql-kafka-0-10_2.12-3.3.1.pom
[2025-08-31 23:32:45,693] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,693] {subprocess.py:92} INFO - 	  -- artifact org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1!spark-sql-kafka-0-10_2.12.jar:
[2025-08-31 23:32:45,693] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,693] {subprocess.py:92} INFO - 	  https://repos.spark-packages.org/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.1/spark-sql-kafka-0-10_2.12-3.3.1.jar
[2025-08-31 23:32:45,693] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,693] {subprocess.py:92} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-08-31 23:32:45,693] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,693] {subprocess.py:92} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-08-31 23:32:45,693] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,694] {subprocess.py:92} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-08-31 23:32:45,694] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,694] {subprocess.py:92} INFO - 		:: org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1: not found
[2025-08-31 23:32:45,694] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,694] {subprocess.py:92} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-08-31 23:32:45,694] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,694] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,694] {subprocess.py:92} INFO - 
[2025-08-31 23:32:45,694] {subprocess.py:92} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-08-31 23:32:45,694] {subprocess.py:92} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.spark#spark-sql-kafka-0-10_2.12;3.3.1: not found]
[2025-08-31 23:32:45,695] {subprocess.py:92} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-08-31 23:32:45,695] {subprocess.py:92} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-08-31 23:32:45,695] {subprocess.py:92} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-08-31 23:32:45,695] {subprocess.py:92} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-08-31 23:32:45,695] {subprocess.py:92} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-08-31 23:32:45,695] {subprocess.py:92} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-08-31 23:32:45,695] {subprocess.py:92} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-08-31 23:32:45,695] {subprocess.py:92} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-08-31 23:32:45,695] {subprocess.py:92} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-08-31 23:32:45,695] {subprocess.py:92} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-08-31 23:32:45,726] {subprocess.py:96} INFO - Command exited with return code 1
[2025-08-31 23:32:45,755] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-31 23:32:45,763] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=send_weather_to_kafka, task_id=stream_hdfs, execution_date=20250829T194201, start_date=20250831T233237, end_date=20250831T233245
[2025-08-31 23:32:45,794] {standard_task_runner.py:97} ERROR - Failed to execute job 380 for task stream_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 188)
[2025-08-31 23:32:45,813] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-08-31 23:32:45,858] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
