[2025-08-18 09:15:47,835] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-08-18T09:15:47.545529+00:00 [queued]>
[2025-08-18 09:15:47,846] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-08-18T09:15:47.545529+00:00 [queued]>
[2025-08-18 09:15:47,846] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-18 09:15:47,846] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-18 09:15:47,846] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-18 09:15:47,863] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_and_send_weather> on 2025-08-18 09:15:47.545529+00:00
[2025-08-18 09:15:47,869] {standard_task_runner.py:52} INFO - Started process 502 to run task
[2025-08-18 09:15:47,874] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'fetch_and_send_weather', 'manual__2025-08-18T09:15:47.545529+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmp8_9vpnfl', '--error-file', '/tmp/tmpmuedu1hi']
[2025-08-18 09:15:47,875] {standard_task_runner.py:80} INFO - Job 269: Subtask fetch_and_send_weather
[2025-08-18 09:15:47,941] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-08-18T09:15:47.545529+00:00 [running]> on host a4b544519f2b
[2025-08-18 09:15:48,081] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=fetch_and_send_weather
AIRFLOW_CTX_EXECUTION_DATE=2025-08-18T09:15:47.545529+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-18T09:15:47.545529+00:00
[2025-08-18 09:15:48,082] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-18 09:15:48,083] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && python3 kafka/producer.py']
[2025-08-18 09:15:48,104] {subprocess.py:85} INFO - Output:
[2025-08-18 09:15:48,805] {subprocess.py:92} INFO - Envoi vers Kafka : {'temperature': 27.5, 'humidity': 85, 'windSpeed': 4.2, 'cloudCover': 100, 'rainIntensity': 0, 'timestamp': '2025-08-18T09:15:00Z'}
[2025-08-18 09:15:48,856] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-18 09:15:48,893] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=fetch_and_send_weather, execution_date=20250818T091547, start_date=20250818T091547, end_date=20250818T091548
[2025-08-18 09:15:48,927] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-18 09:15:48,965] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
